#!/bin/sh -e

# Create a "Release"

ver="$1"

# Parse command line parameter
if [ -z "$ver" ]
then
	ver=`date +"%Y%m%d%H%M%S"`
	echo "Using version: $ver"
fi

TAG="v$ver"
BRANCH="release-$ver"

# Tag and push tags 
git tag -a "$TAG" -m "Release $TAG"
git push origin "$TAG"

# Also create a release branch
git checkout -b "$BRANCH"
git push origin "$BRANCH"

# Back to master
git checkout master
